### PR TITLE
Bug fixes for diochan

### PR DESCRIPTION
**Pull request by bloatmode**
I would share the compiled .apk, but I imagine having a different signature from yours would cause problems with updates.

### CODE REVIEW

**Comment by yavernoxia** [comment]
May I get the compiled apk somewhere!

**Comment by f77** [comment]
Hello, man. I have been changed only 2ch.hk imageboard in this fork.
There is nothing changes for diochan.

**Comment by bloatmode** [comment]
Ok, so does that mean that I can compile the .apk, upload it to update/package and edit data.json? What is the fingerprint associated to each package in data.json?

**Comment by f77** [comment]
I don't quite understand what you want...
>What is the fingerprint associated to each package in data.json?

This is the sha256 hash of signature of the client app.
The client app always checks its own signature hash and the signature hash in the data.json and blocks an update if a comparison was failed.

**Comment by bloatmode** [comment]
> I don't quite understand what you want...

I'd like you to merge my fixes for the diochan extension (Mishiranu's version couldn't post on /b/, and it stopped working since diochan.com started using https), compile the apk and sign it with the same key you used for dashchan, and then upload the apk to the master branch

**Comment by bloatmode** [comment]
Hello? Could you please merge my changes and build the signed .apk?

**Comment by f77** [comment]
Sorry, I just don't have time to do this. I'll merge it when I find time. Please, be patient.

**Comment by f77** [comment]
Ok, I have merged it, but it still works with very big delays.
The behavior in a browser is similar.

**Pull request merged**
